version: '1.0'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass passcode
    ports:
      - "6379:6379"
    
    volumes:
      - $PWD/redisdata:/var/lib/redis
      - $PWS/redis.conf:/usr/local/etc/redis/redis.conf

  